### ISSUE TITLE
[4월 3주차] TODO

### ISSUE THREAD

**Issue by leeleelee3264** [leeleelee3264/java_toy_project#1]
- [ ] 트위터 프로젝트 한 것 정리해서 블로깅
- [ ] git/linux 커맨드 업데이트 
- [ ] 집에서 서버 판 거 정리해서 블로깅 
- [ ] 이번에 docker랑 docker compose 이용한거 정리해서 블로깅 (로컬 코드 고치기 requirements.txt 업데이트 문제) 
- [ ] 자바인 액션 제발 나머지 부분 읽기 (50페이지라도 읽어보세요,,,)
